nginx conf

diff --git a/scripts/install b/scripts/install
--- a/scripts/install
+++ b/scripts/install
@@ -12,6 +12,13 @@ if [[ ! $? -eq 0 ]]; then
 exit 1
 fi
 
+# Check that admin user is an existing account
+sudo yunohost user list --json | grep -q "\"username\": \"$admin_user\""
+if [[ ! $? -eq 0 ]]; then
+    echo "Error : the chosen admin user does not exist"
+    exit 1
+fi
+
 # Generate random password
 db_pwd=$(dd if=/dev/urandom bs=1 count=200 2> /dev/null | tr -c -d 'A-Za-z0-9' | sed -n 's/\(.\{24\}\).*/\1/p')
 
@@ -42,7 +49,10 @@ sudo chown -R www-data: $final_path
 # Modify Nginx configuration file and copy it to Nginx conf directory
 sed -i "s@PATHTOCHANGE@$path@g" ../conf/nginx.conf*
 sed -i "s@ALIASTOCHANGE@$final_path/@g" ../conf/nginx.conf*
-sudo cp ../conf/nginx.conf /etc/nginx/conf.d/$domain.d/yourls.conf
+nginxconf=/etc/nginx/conf.d/$domain.d/yourls.conf
+sudo cp ../conf/nginx.conf $nginxconf
+sudo chown root: $nginxconf
+sudo chmod 600 $nginxconf
 
 # Reload Nginx and regenerate SSOwat conf
 sudo service nginx reload
